name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.target.machine }}
    strategy:
      matrix:
        target:
          - machine: macos-latest
            architecture: arm64
            shell: bash
            packageManager: brew
          - machine: macos-15
            architecture: x86_64
            shell: bash
            packageManager: brew
          - machine: macos-latest
            architecture: arm64
            shell: bash
            packageManager: macport
          - machine: ubuntu-latest
            architecture: x86_64
            shell: bash
            packageManager: default
          - machine: ubuntu-22.04-arm
            architecture: arm64
            shell: bash
            packageManager: default
          - machine: ubuntu-24.04-arm
            architecture: arm64
            shell: bash
            packageManager: default
      fail-fast: false
    defaults:
     run:
      shell: ${{ matrix.target.shell }} {0}

    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu packages
      if: startsWith(matrix.target.machine, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get -y install texinfo bison flex gettext libgmp3-dev libmpfr-dev libmpc-dev

    - name: Install macOS packages with brew
      if: startsWith(matrix.target.machine, 'macos') && matrix.target.packageManager == 'brew'
      run: |
        brew update
        brew install texinfo bison flex gnu-sed gsl gmp mpfr libmpc zlib libiconv

    - name: Install macOS packages with macport
      if: startsWith(matrix.target.machine, 'macos') && matrix.target.packageManager == 'macport'
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        source ./macports-ci install --remove-brew --version=2.11.5 --sync=rsync
         sudo port install gmp mpfr libmpc libiconv bison flex texinfo zlib

    - name: Install MSYS2 packages
      if: startsWith(matrix.target.machine, 'windows')
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: |
          base-devel git make texinfo flex bison patch binutils mpc-devel tar
          mingw-w64-i686-readline mingw-w64-i686-gcc 
          mingw-w64-i686-cmake mingw-w64-i686-make mingw-w64-i686-libogg
        update: true

    - name: Runs all stages
      run: |
        export PSPDEV=$PWD/pspdev
        export PATH=$PATH:$PSPDEV/bin
        ./toolchain.sh
    
    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
    
    - name: Compress pspdev folder
      run: |
        tar -zcvf pspdev.tar.gz pspdev
    
    - uses: actions/upload-artifact@v4
      with:
        name: pspdev-${{ steps.slug.outputs.sha8 }}-${{ matrix.target.machine }}
        path: pspdev.tar.gz

  build-docker:
    runs-on: ubuntu-latest
    container: ${{ matrix.os[0] }}:${{ matrix.os[2] }}
    strategy:
      matrix:
        os: [[ubuntu, bash, latest], [fedora, bash, latest]]
    steps:
    - name: Install dependencies Ubuntu
      if: matrix.os[0] == 'ubuntu'
      run: |
        apt-get -y update
        DEBIAN_FRONTEND="noninteractive" TZ="Europe/London" apt-get -y install file bison make flex texinfo gettext \
          g++ gcc git libgmp3-dev libmpfr-dev libmpc-dev libncurses5-dev
    
    - name: Install dependencies Fedora
      if: matrix.os[0] == 'fedora'
      run: |
        dnf -y install gcc gcc-c++ make git gettext texinfo bison flex gmp-devel mpfr-devel libmpc-devel \
          ncurses-devel diffutils glibc-gconv-extra which gawk file

    - name: Checkout git repo
      uses: actions/checkout@v4
    
    - name: Runs all the stages in the shell
      run: |
        chown -R $(id -nu):$(id -ng) .
        export PSPDEV=$PWD/pspdev
        export PATH=$PATH:$PSPDEV/bin
        ./toolchain.sh
        
    - name: Get short SHA
      id: slug
      run: |
        echo "sha8=${MSYSTEM}-sha[$(echo ${GITHUB_SHA} | cut -c1-8)]" >> $GITHUB_OUTPUT

    - name: Prepare pspdev folder
      run: |
        tar -zcvf pspdev-${{matrix.os[0]}}.tar.gz pspdev

    - uses: actions/upload-artifact@v4
      with:
        name: pspdev-${{matrix.os[0]}}-pspdev-${{matrix.os[2]}}-${{ steps.slug.outputs.sha8 }}
        path: pspdev-${{matrix.os[0]}}.tar.gz